# Computing on Data

In [98]:
A = [1 2; 3 4; 5 6]

A =

     1     2
     3     4
     5     6


In [99]:
B = [11 12; 13 14; 15 16]

B =

    11    12
    13    14
    15    16


In [100]:
C = [1 1; 2 2]

C =

     1     1
     2     2


In [101]:
A * C

ans =

     5     5
    11    11
    17    17


In [102]:
A .* B

ans =

    11    24
    39    56
    75    96


In [103]:
A .^ 2

ans =

     1     4
     9    16
    25    36


In [104]:
v = [1; 2; 3]

v =

     1
     2
     3


In [105]:
1 ./ A

ans =

    1.0000    0.5000
    0.3333    0.2500
    0.2000    0.1667


In [106]:
log(v)

ans =

         0
    0.6931
    1.0986


In [107]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855


In [108]:
abs(v)

ans =

     1
     2
     3


In [109]:
abs([-1; 2; -3])

ans =

     1
     2
     3


In [110]:
-v

ans =

    -1
    -2
    -3


In [111]:
v + ones(length(v), 1)

ans =

     2
     3
     4


In [112]:
v + 1

ans =

     2
     3
     4


In [113]:
A

A =

     1     2
     3     4
     5     6


In [114]:
A'

ans =

     1     3     5
     2     4     6


In [115]:
(A')'

ans =

     1     2
     3     4
     5     6


In [116]:
a = [1 15 2 0.5]

a =

    1.0000   15.0000    2.0000    0.5000


In [117]:
val = max(a)

val =

    15


In [118]:
[val, index] = max(a)

val =

    15


index =

     2


In [119]:
max(A)

ans =

     5     6


In [120]:
a < 3

ans =

     1     0     1     1


In [121]:
find(a < 3)

ans =

     1     3     4


In [122]:
A = magic(3)

A =

     8     1     6
     3     5     7
     4     9     2


In [123]:
[row, column] = find(A >= 7)

row =

     1
     3
     2


column =

     1
     2
     3


In [124]:
a 

a =

    1.0000   15.0000    2.0000    0.5000


In [125]:
sum(a)

ans =

   18.5000


In [126]:
prod(a) %a1*a2*a3*a4

ans =

    15


In [127]:
floor(a)

ans =

     1    15     2     0


In [128]:
ceil(a)

ans =

     1    15     2     1


In [129]:
rand(3)

ans =

    0.3922    0.7060    0.0462
    0.6555    0.0318    0.0971
    0.1712    0.2769    0.8235


In [130]:
max(rand(3), rand(3))

ans =

    0.6948    0.7094    0.7655
    0.4456    0.7547    0.7952
    0.9502    0.3816    0.1869


In [131]:
A

A =

     8     1     6
     3     5     7
     4     9     2


In [132]:
max(A, [], 1)

ans =

     8     9     7


In [133]:
max(A, [], 2)

ans =

     8
     7
     9


In [134]:
max(A)

ans =

     8     9     7


In [135]:
A = magic(9)

A =

    47    58    69    80     1    12    23    34    45
    57    68    79     9    11    22    33    44    46
    67    78     8    10    21    32    43    54    56
    77     7    18    20    31    42    53    55    66
     6    17    19    30    41    52    63    65    76
    16    27    29    40    51    62    64    75     5
    26    28    39    50    61    72    74     4    15
    36    38    49    60    71    73     3    14    25
    37    48    59    70    81     2    13    24    35


In [136]:
sum(A, 1)

ans =

   369   369   369   369   369   369   369   369   369


In [137]:
sum(A, 2)

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369


In [138]:
A .* eye(9)

ans =

    47     0     0     0     0     0     0     0     0
     0    68     0     0     0     0     0     0     0
     0     0     8     0     0     0     0     0     0
     0     0     0    20     0     0     0     0     0
     0     0     0     0    41     0     0     0     0
     0     0     0     0     0    62     0     0     0
     0     0     0     0     0     0    74     0     0
     0     0     0     0     0     0     0    14     0
     0     0     0     0     0     0     0     0    35


In [139]:
sum(sum(A .* eye(9)))

ans =

   369


In [140]:
flipud(eye(9))

ans =

     0     0     0     0     0     0     0     0     1
     0     0     0     0     0     0     0     1     0
     0     0     0     0     0     0     1     0     0
     0     0     0     0     0     1     0     0     0
     0     0     0     0     1     0     0     0     0
     0     0     0     1     0     0     0     0     0
     0     0     1     0     0     0     0     0     0
     0     1     0     0     0     0     0     0     0
     1     0     0     0     0     0     0     0     0


In [141]:
A = magic(3)

A =

     8     1     6
     3     5     7
     4     9     2


In [142]:
pinv(A)

ans =

    0.1472   -0.1444    0.0639
   -0.0611    0.0222    0.1056
   -0.0194    0.1889   -0.1028


In [143]:
temp = pinv(A)

temp =

    0.1472   -0.1444    0.0639
   -0.0611    0.0222    0.1056
   -0.0194    0.1889   -0.1028


In [144]:
temp * A

ans =

    1.0000    0.0000   -0.0000
   -0.0000    1.0000    0.0000
    0.0000    0.0000    1.0000
